
#pragma once

.decl global_function(name: symbol, signature: irType<>)

global_function("parseInt", $Function($Integer(), [$String(), nil])).
global_function("assert", $Function($Void(), [$Boolean(), nil])).

inferred_type(symbol, type) :-
    // TODO: make sure this is inface a global function and not a symbol used in a load
    vertex(symbol, "Symbol", _, callee_name),
    global_function(callee_name, type).
